<a href="https://colab.research.google.com/github/Jerathaditya/TCS-iON/blob/main/Mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from keras.datasets import fashion_mnist

from keras.utils.np_utils import to_categorical

(trainX,trainy),(testX,testy)=fashion_mnist.load_data()

def load_dataset():
    (trainX,trainy),(testX,testy)=fashion_mnist.load_data()
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((testX.shape[0], 28, 28, 1))
    trainy = to_categorical(trainy)
    testy = to_categorical(testy)
    return trainX, trainy, testX, testy

seed = 9
from sklearn.model_selection import StratifiedShuffleSplit

data_split = StratifiedShuffleSplit(test_size = 0.5, random_state = seed)
for train_index, test_index in data_split.split(trainX, trainy):
    split_data_92, split_data_8 = trainX[train_index], trainX[test_index]
    split_label_92, split_label_8 = trainy[train_index], trainy[test_index]
train_test_split = StratifiedShuffleSplit(test_size = 0.3, random_state = seed)

for train_index, test_index in train_test_split.split(split_data_8, split_label_8):
    train_data_70, test_data_30 = split_data_8[train_index], split_data_8[test_index]
    train_label_70, test_label_30 = split_label_8[train_index], split_label_8[test_index]

train_data = train_data_70
train_label = train_label_70

test_data = test_data_30
test_label = test_label_30

print('train_data : ', train_data.shape)
print('train_label : ', train_label.shape)
print('test_data : ', test_data.shape)
print('test_label : ', test_label.shape)

train_data = train_data.astype('float64') / 255.0
test_data = test_data.astype('float64') / 255.0

print('train_data : ', train_data.shape)
print('test_data : ', test_data.shape)

train_data_flat = train_data.reshape(train_data.shape[0], -1) 
test_data_flat = test_data.reshape(test_data.shape[0], -1)

print('train_data_flat : ', train_data_flat.shape)
print('test_data_flat : ', test_data_flat.shape)

train_data_flat_t = train_data_flat
test_data_flat_t = test_data_flat

from sklearn.decomposition import PCA
train_data_pca = PCA(n_components = min(train_data_flat_t.shape)).fit_transform(train_data_flat_t)
test_data_pca = PCA(n_components = min(test_data_flat_t.shape)).fit_transform(test_data_flat_t)

print(train_data_pca.shape)
print(test_data_pca.shape)



from skimage import color
def svdFeatures(input_data):
    svdArray_input_data = []
    size = input_data.shape[0]
    for i in range(0, size):

        U, s, V = np.linalg.svd(input_data[i], full_matrices = False)
        S = [s[i] for i in range(28)]
        svdArray_input_data.append(s)
        svdMatrix_input_data = np.matrix(svdArray_input_data)
    return svdMatrix_input_data

train_data_svd = svdFeatures(train_data)
test_data_svd = svdFeatures(test_data)

print(train_data_svd.shape)
print(test_data_svd.shape)
        
        
    

from sklearn.neural_network import MLPClassifier
from sklearn import metrics
def train_test(train_dataset, test_dataset):
    
    MLP = MLPClassifier()
    train = MLP.fit(train_dataset, train_label)
    
    mlp_predict = MLP.predict(test_dataset)
    score = MLP.score(test_dataset, test_label)
    print('score : ', score)
    conf_matrix = metrics.confusion_matrix(test_label, mlp_predict)
    print('Confusion Matrix: ', conf_matrix)
    

train_test(train_data_flat_t, test_data_flat_t)

train_test(train_data_pca, test_data_pca)


train_test(train_data_svd, test_data_svd)



train_data :  (21000, 28, 28)
train_label :  (21000,)
test_data :  (9000, 28, 28)
test_label :  (9000,)
train_data :  (21000, 28, 28)
test_data :  (9000, 28, 28)
train_data_flat :  (21000, 784)
test_data_flat :  (9000, 784)
(21000, 784)
(9000, 784)
(21000, 28)
(9000, 28)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


score :  0.8672222222222222
Confusion Matrix:  [[699   5  22  30   6   3 130   0   5   0]
 [  2 876   1  14   3   0   4   0   0   0]
 [ 14   0 674   6 108   1  86   1  10   0]
 [ 28  13  16 778  32   0  31   0   2   0]
 [  3   1  64  27 729   0  65   0  10   1]
 [  1   0   0   0   0 848   0  34   2  15]
 [117   3  53  27  53   0 636   0  11   0]
 [  0   0   0   0   0  13   0 861   4  22]
 [  7   3   4   6   2  10  11   2 854   1]
 [  1   1   0   0   1   7   1  39   0 850]]
score :  0.29244444444444445
Confusion Matrix:  [[584  12  58  50  25  22 132   1   9   7]
 [ 28 507  13 333   7   5   5   0   2   0]
 [108  17 126  62 115  77  75   9 179 132]
 [185  99 178 219 145   8  61   2   3   0]
 [ 72  28 127  41 221  25 132  19 131 104]
 [  5   1  13  15   5 315  20 328 102  96]
 [215  18 110  61  76  65 168  11  60 116]
 [ 14  17   9   1  23 230   1 365 213  27]
 [ 13  37  56   9  85  78  90 122 117 293]
 [  0   0 123   0  76 289 137  56 209  10]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


score :  0.6336666666666667
Confusion Matrix:  [[471   0  66  81  37  10  94   9  84  48]
 [  6 701   1 100   8   9   3  61   6   5]
 [ 77   1 438  14 112   8 140   4  96  10]
 [ 28 112  37 464  44  31  19 102  51  12]
 [ 46   8 153  88 390   6 133   9  50  17]
 [  5   9   1   5   2 709  15 128  11  15]
 [133   1 110  57 106  15 347   5 115  11]
 [  4  10   0  22   1  97   2 709   8  47]
 [ 19   3  22  36  15  15  35  21 731   3]
 [ 36   2   2   1   7  12  14  78   5 743]]
