<a href="https://colab.research.google.com/github/Jerathaditya/TCS-iON/blob/main/Naive_beyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from keras.datasets import fashion_mnist

from keras.utils.np_utils import to_categorical

(trainX,trainy),(testX,testy)=fashion_mnist.load_data()

def load_dataset():
    (trainX,trainy),(testX,testy)=fashion_mnist.load_data()
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((testX.shape[0], 28, 28, 1))
    trainy = to_categorical(trainy)
    testy = to_categorical(testy)
    return trainX, trainy, testX, testy

seed = 9
from sklearn.model_selection import StratifiedShuffleSplit

data_split = StratifiedShuffleSplit(test_size = 0.5, random_state = seed)
for train_index, test_index in data_split.split(trainX, trainy):
    split_data_92, split_data_8 = trainX[train_index], trainX[test_index]
    split_label_92, split_label_8 = trainy[train_index], trainy[test_index]
train_test_split = StratifiedShuffleSplit(test_size = 0.3, random_state = seed)

for train_index, test_index in train_test_split.split(split_data_8, split_label_8):
    train_data_70, test_data_30 = split_data_8[train_index], split_data_8[test_index]
    train_label_70, test_label_30 = split_label_8[train_index], split_label_8[test_index]

train_data = train_data_70
train_label = train_label_70

test_data = test_data_30
test_label = test_label_30

print('train_data : ', train_data.shape)
print('train_label : ', train_label.shape)
print('test_data : ', test_data.shape)
print('test_label : ', test_label.shape)

train_data = train_data.astype('float64') / 255.0
test_data = test_data.astype('float64') / 255.0

print('train_data : ', train_data.shape)
print('test_data : ', test_data.shape)

train_data_flat = train_data.reshape(train_data.shape[0], -1)
test_data_flat = test_data.reshape(test_data.shape[0], -1)

print('train_data_flat : ', train_data_flat.shape)
print('test_data_flat : ', test_data_flat.shape)

train_data_flat_t = train_data_flat
test_data_flat_t = test_data_flat

from sklearn.decomposition import PCA
train_data_pca = PCA(n_components = min(train_data_flat_t.shape)).fit_transform(train_data_flat_t)
test_data_pca = PCA(n_components = min(test_data_flat_t.shape)).fit_transform(test_data_flat_t)

print(train_data_pca.shape)
print(test_data_pca.shape)



from skimage import color
def svdFeatures(input_data):
    svdArray_input_data = []
    size = input_data.shape[0]
    for i in range(0, size):
#         img = color.rgb2gray(input_data[i])
        U, s, V = np.linalg.svd(input_data[i], full_matrices = False)
        S = [s[i] for i in range(28)]
        svdArray_input_data.append(s)
        svdMatrix_input_data = np.matrix(svdArray_input_data)
    return svdMatrix_input_data

train_data_svd = svdFeatures(train_data)
test_data_svd = svdFeatures(test_data)

print(train_data_svd.shape)
print(test_data_svd.shape)
        
        
    


from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
def train_test(train_dataset, test_dataset):
    
    gnb = GaussianNB()
    train = gnb.fit(train_dataset, train_label)
    
    y_pred = gnb.predict(test_dataset)
    score = gnb.score(test_dataset, test_label)
    print('score : ', score)
    conf_matrix = metrics.confusion_matrix(test_label, y_pred)
    print('Confusion Matrix: ', conf_matrix)

train_test(train_data_flat_t, test_data_flat_t)

train_test(train_data_svd, test_data_svd) 

train_test(train_data_pca, test_data_pca)




train_data :  (21000, 28, 28)
train_label :  (21000,)
test_data :  (9000, 28, 28)
test_label :  (9000,)
train_data :  (21000, 28, 28)
test_data :  (9000, 28, 28)
train_data_flat :  (21000, 784)
test_data_flat :  (9000, 784)
(21000, 784)
(9000, 784)
(21000, 28)
(9000, 28)
score :  0.591
Confusion Matrix:  [[498   1  29 269  49   0  21   0  33   0]
 [  0 654   7 233   1   0   4   0   1   0]
 [  2   0 345  96 414   0  26   0  17   0]
 [  5   0   9 857  18   0   6   0   5   0]
 [  1   1  54 219 614   0   5   0   6   0]
 [  0   0   3   1   0 244   5 600   8  39]
 [ 92   2 111 278 340   0  36   0  41   0]
 [  0   0   0   0   0   5   0 884   4   7]
 [  1   0  61 101 100   9  11   2 614   1]
 [  1   0   2   3   1  11   1 303   5 573]]
score :  0.316
Confusion Matrix:  [[ 92 169  15 218 137  10  16 124  18 101]
 [  2 826   0   7   4   0   2  54   0   5]
 [ 35 100  46 271 193  11  11 143  16  74]
 [  4 533   1  76  29  13   1 202   3  38]
 [ 21  77   7 203 373  14  12 110  10  73]
 [  5 203   0 